"""Image generation. Three outputs, three reliability tiers:

  clean_white_bg()    -> Real product pixels, white background.
                         Photoroom is strongest; rembg is a local low-cost option.
                         This is your safe primary catalog image.

  generate_lifestyle()-> BEST-EFFORT. The exact product in a simple ecommerce scene
                         without hands/model complexity.

  generate_on_model() -> BEST-EFFORT. A model using/holding/wearing the product, generated by a
                         reference-conditioned image model (image edits:
                         the real product photo is the input, so the product is preserved
                         rather than hallucinated). Returns several candidates;
                         a human picks the good ones before publish. Some outputs
                         WILL mangle hardware/logo or warp the product near hands —
                         that's expected, hence candidates + review.

Claude does NOT generate images — the generated-image provider is OpenAI here.
To move to Gemini later, reimplement the edit helper only; orchestration stays.
"""

import asyncio
import base64
import io
from pathlib import Path

import httpx
from openai import OpenAI
from PIL import Image, ImageFilter, ImageOps

from app.config import settings
from app.product_types.prompts import BAG_PROMPT_PACK, ProductPromptPack

_openai = OpenAI(api_key=settings.openai_api_key) if settings.openai_api_key else None

_EXT_BY_MEDIA_TYPE = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
}


# Longest-side cap for provider uploads. Phone photos run 4000-6000px / 4-6MB,
# which trips Pixelcut's file-size limit; 2048px is well above what any downstream
# needs (cutouts + gpt-image outputs top out at 1536px) and keeps uploads small.
_MAX_UPLOAD_DIM = 2048


def _to_png(image_bytes: bytes) -> bytes:
    """Normalize + downscale uploads for providers that reject large/odd images."""
    with Image.open(io.BytesIO(image_bytes)) as image:
        image = ImageOps.exif_transpose(image)
        if image.mode not in ("RGB", "RGBA"):
            image = image.convert("RGBA" if "A" in image.getbands() else "RGB")

        longest = max(image.size)
        if longest > _MAX_UPLOAD_DIM:
            scale = _MAX_UPLOAD_DIM / longest
            new_size = (round(image.width * scale), round(image.height * scale))
            image = image.resize(new_size, Image.LANCZOS)

        output = io.BytesIO()
        image.save(output, format="PNG")
        return output.getvalue()


# --- Background removal + local compositing ---------------------------------

async def clean_white_bg(image_bytes: bytes, media_type: str) -> bytes:
    """Product composited onto a clean white background."""
    cutout = await remove_background(image_bytes, media_type)
    return composite_on_white(cutout)


async def remove_background(image_bytes: bytes, media_type: str) -> bytes:
    """Return a transparent PNG cutout from the configured background remover."""
    backend = settings.background_remover.lower().strip()
    if backend == "rembg":
        return await _remove_background_rembg(image_bytes)
    if backend == "photoroom":
        return await _remove_background_photoroom(image_bytes)
    if backend == "pixelcut":
        return await _remove_background_pixelcut(image_bytes, media_type)
    raise RuntimeError(
        "BACKGROUND_REMOVER must be 'photoroom', 'pixelcut', or 'rembg' "
        f"(got {settings.background_remover!r})"
    )


def composite_on_white(cutout_bytes: bytes) -> bytes:
    """Composite a transparent PNG cutout onto a white PNG background."""
    with Image.open(io.BytesIO(cutout_bytes)) as cutout:
        cutout = ImageOps.exif_transpose(cutout).convert("RGBA")
        white = Image.new("RGBA", cutout.size, (255, 255, 255, 255))
        white.alpha_composite(cutout)
        output = io.BytesIO()
        white.convert("RGB").save(output, format="PNG")
        return output.getvalue()


def _trim_transparent_padding(image: Image.Image) -> Image.Image:
    bbox = image.getchannel("A").getbbox()
    return image.crop(bbox) if bbox else image


def compose_on_backdrop(
    cutout_bytes: bytes,
    backdrop_path: str | Path,
    size: int = 2000,
    fill: float = 0.72,
    shadow_opacity: int = 90,
    shadow_blur: int = 40,
    shadow_offset: float = 0.025,
    image_format: str = "jpg",
    quality: int = 90,
) -> bytes:
    """Place a transparent product cutout on a square studio backdrop."""
    if size <= 0:
        raise ValueError("size must be greater than 0")
    if fill <= 0:
        raise ValueError("fill must be greater than 0")

    with Image.open(backdrop_path) as backdrop:
        canvas = ImageOps.fit(
            ImageOps.exif_transpose(backdrop).convert("RGB"),
            (size, size),
            method=Image.Resampling.LANCZOS,
            centering=(0.5, 0.5),
        ).convert("RGBA")

    with Image.open(io.BytesIO(cutout_bytes)) as cutout:
        product = _trim_transparent_padding(
            ImageOps.exif_transpose(cutout).convert("RGBA")
        )

    max_side = max(product.size)
    target_side = max(1, int(size * fill))
    scale = target_side / max_side
    product_size = (
        max(1, int(product.width * scale)),
        max(1, int(product.height * scale)),
    )
    product = product.resize(product_size, Image.Resampling.LANCZOS)

    x = (size - product.width) // 2
    y = (size - product.height) // 2
    alpha = product.getchannel("A")
    shadow_y = y + int(size * shadow_offset)
    shadow_alpha = Image.new("L", canvas.size, 0)
    shadow_alpha.paste(alpha, (x, shadow_y))
    opacity = max(0, min(255, shadow_opacity))
    shadow_alpha = shadow_alpha.point(lambda pixel: pixel * opacity // 255)
    if shadow_blur > 0:
        shadow_alpha = shadow_alpha.filter(ImageFilter.GaussianBlur(shadow_blur))

    shadow_layer = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    shadow_layer.putalpha(shadow_alpha)
    canvas.alpha_composite(shadow_layer)
    canvas.alpha_composite(product, (x, y))

    output = io.BytesIO()
    normalized_format = image_format.lower().strip()
    if normalized_format in {"jpg", "jpeg"}:
        canvas.convert("RGB").save(output, format="JPEG", quality=quality, optimize=True)
    elif normalized_format == "png":
        canvas.save(output, format="PNG", optimize=True)
    else:
        raise ValueError("image_format must be 'jpg' or 'png'")
    return output.getvalue()


async def _remove_background_rembg(image_bytes: bytes) -> bytes:
    """Local background removal using rembg."""
    upload_bytes = _to_png(image_bytes)

    def _call() -> bytes:
        try:
            from rembg import remove
        except ImportError as exc:
            raise RuntimeError(
                "rembg is not installed. Run: pip install -r requirements.txt"
            ) from exc

        cutout_bytes = remove(upload_bytes)
        with Image.open(io.BytesIO(cutout_bytes)) as cutout:
            cutout = ImageOps.exif_transpose(cutout).convert("RGBA")
            output = io.BytesIO()
            cutout.save(output, format="PNG")
            return output.getvalue()

    return await asyncio.to_thread(_call)


async def _remove_background_photoroom(image_bytes: bytes) -> bytes:
    """Return a transparent PNG cutout using Photoroom Basic.

    Photoroom Remove Background API:
        POST https://sdk.photoroom.com/v1/segment
        headers: {"x-api-key": settings.photoroom_api_key}
        files:   {"image_file": (filename, image_bytes, media_type)}
        -> transparent-background PNG bytes in the response body

    """
    if not settings.photoroom_api_key:
        raise RuntimeError("PHOTOROOM_API_KEY is not configured")

    upload_bytes = _to_png(image_bytes)
    last_exc: Exception | None = None
    async with httpx.AsyncClient(timeout=60) as client:
        for attempt in range(3):
            try:
                response = await client.post(
                    "https://sdk.photoroom.com/v1/segment",
                    headers={"x-api-key": settings.photoroom_api_key},
                    files={"image_file": ("product.png", upload_bytes, "image/png")},
                )
                break
            except (
                httpx.ConnectError,
                httpx.ReadError,
                httpx.RemoteProtocolError,
                httpx.TimeoutException,
            ) as exc:
                last_exc = exc
                if attempt == 2:
                    raise
                await asyncio.sleep(1 + attempt)
        else:
            raise RuntimeError(f"Photoroom failed before response: {last_exc}")

    if response.status_code >= 400:
        raise RuntimeError(
            f"Photoroom failed with {response.status_code}: {response.text}"
        )

    return _normalize_cutout_png(response.content)


async def _remove_background_pixelcut(image_bytes: bytes, media_type: str) -> bytes:
    """Return a transparent PNG cutout using Pixelcut."""
    if not settings.pixelcut_api_key:
        raise RuntimeError("PIXELCUT_API_KEY is not configured")

    upload_bytes = _to_png(image_bytes)
    last_exc: Exception | None = None
    async with httpx.AsyncClient(timeout=90) as client:
        for attempt in range(3):
            try:
                response = await client.post(
                    "https://api.developer.pixelcut.ai/v1/remove-background",
                    headers={
                        "X-API-KEY": settings.pixelcut_api_key,
                        "Accept": "image/*",
                    },
                    data={"format": "png", "crop": "false"},
                    files={"image": ("product.png", upload_bytes, "image/png")},
                )
                break
            except (
                httpx.ConnectError,
                httpx.ReadError,
                httpx.RemoteProtocolError,
                httpx.TimeoutException,
            ) as exc:
                last_exc = exc
                if attempt == 2:
                    raise
                await asyncio.sleep(1 + attempt)
        else:
            raise RuntimeError(f"Pixelcut failed before response: {last_exc}")

        if response.status_code >= 400:
            raise RuntimeError(
                f"Pixelcut failed with {response.status_code}: {response.text}"
            )

        content_type = response.headers.get("content-type", "").lower()
        if "application/json" in content_type:
            result_url = response.json().get("result_url")
            if not result_url:
                raise RuntimeError("Pixelcut JSON response did not include result_url")
            result = await client.get(result_url, headers={"Accept": "image/*"})
            if result.status_code >= 400:
                raise RuntimeError(
                    f"Pixelcut result download failed with "
                    f"{result.status_code}: {result.text}"
                )
            return _normalize_cutout_png(result.content)

        return _normalize_cutout_png(response.content)


def _normalize_cutout_png(image_bytes: bytes) -> bytes:
    with Image.open(io.BytesIO(image_bytes)) as cutout:
        cutout = ImageOps.exif_transpose(cutout).convert("RGBA")
        output = io.BytesIO()
        cutout.save(output, format="PNG")
        return output.getvalue()


# --- Best-effort generated shots (reference-conditioned image editing) -------

PRODUCT_FIDELITY_RULES = """Product fidelity rules:
- If multiple reference photos are provided, they are different angles of the same exact product. Use all of them to understand the product's true 3D shape, side profile, handle/strap placement, depth, hardware, texture, and proportions. Do not combine them into multiple products.
- Preserve the exact outer silhouette and proportions of the reference product. If the reference is heart-shaped, crescent, boxy, rectangular, rounded, slouchy, structured, mini, oversized, or asymmetrical, the generated product must keep that same shape.
- Do not stretch, slim, widen, round off, square off, or simplify the bag. Do not change handle height, flap shape, clasp placement, strap attachment points, chain length, side profile, corner radius, or base width.
- Keep distinctive details in the same locations: clasp, lock, logo, seams, stitches, studs, beads, rhinestones, quilting, pleats, panels, piping, handles, strap, feet, zipper, and hardware.
- Treat the uploaded image as a product reference, not design inspiration. The scene may change, but the product design may not."""

LIFESTYLE_PRODUCT_PROMPT = """Product picture with no model
Using the uploaded product photo as reference, create a clean, high-end ecommerce product photograph of the same handbag.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. This is a product listing image, not a stylized reinterpretation.
- Adapt the background tone, lighting warmth, and shadow style to complement the bag's natural color palette. A warm leather bag should sit on a warm-toned backdrop; a cool-toned bag on a softer neutral. Each product photo should feel cohesive with its own product, not a uniform template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: The handbag presented on its own as the sole subject. No model, no hands, no extra props. The bag is upright and styled naturally (handles resting, slight side angle showing depth and profile).

Composition: Bag centered in frame with breathing room on all sides. Three-quarter front angle so handles, body, and one side panel are all visible. Slight elevation - shot just above the bag's midpoint.

Background: Seamless, minimal, lightly textured surface (linen, matte paper, soft plaster, or warm stone). Tone selected to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side to give depth. Highlights catch the leather grain, fabric weave, or hardware. Bright enough to show true color, soft enough to avoid harsh reflections.

Mood: Premium, editorial, clean - like a Mansur Gavriel, Polene, or Brother Vellies catalog image.

Style: High-end commercial product photography, photorealistic, sharp focus on the product, shallow depth of field, natural grain. Colors must be true-to-life (no over-saturation or filter look).

Aspect ratio: 1:1 (square, for product grid).
Resolution: high detail, every stitch and texture visible."""

ON_MODEL_PROMPT = """Product picture with model
Using the uploaded product photo as reference, create a high-end ecommerce lifestyle product photograph featuring the same handbag worn by a model.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. The bag is the primary subject; the model is there to provide scale and styling context.
- Adapt the background tone, wardrobe colors, and lighting warmth to complement the bag's natural color palette. Each generated photo should feel cohesive with its specific product, not a repeating template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: A confident Black woman in her late 20s, shown from chest to mid-thigh (the bag must be fully visible and centered in the frame). She is holding the bag naturally - by the top handle at her side, on her shoulder, or in the crook of her arm, depending on the bag style. Her pose is relaxed and elegant, not overly posed. Face may be partially cropped or shown - prioritize the bag's visibility.

Wardrobe: Elegant, modern outfit in neutral or complementary tones (cream, beige, soft brown, muted terracotta, or off-white). Subtle African print accent allowed (a sleeve detail, scarf, or trim) but the outfit should NOT compete with the bag. Simple, clean silhouette.

Composition: Vertical or square framing. Model slightly off-center to leave breathing room. Bag positioned at the visual focal point, roughly center of frame. Three-quarter front angle on the bag so handles, body, and side profile are visible.

Background: Seamless, minimal, lightly textured surface (warm plaster wall, soft linen backdrop, or stone). Tone chosen to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side for depth. Highlights catch the bag's leather grain, fabric weave, and hardware. True-to-life color on the bag - no filters or color shifts that would misrepresent the product.

Mood: Premium, editorial, modern - like a Polene, Mansur Gavriel, or Brother Vellies lifestyle campaign.

Style: High-end commercial fashion photography, photorealistic, sharp focus on the bag, shallow depth of field. Slight imperfections, natural skin texture, realistic hands holding the bag correctly.

Aspect ratio: 4:5 (vertical, for product grid and listing pages).
Resolution: high detail, every stitch and texture on the bag visible.

Run one bag at a time with a single reference photo for best fidelity. Close attention to anatomically correct hands holding the bag handle. Generate variation through natural pose only: one candidate holding by the handle, one candidate with the bag on the shoulder where appropriate, one detail-oriented product-forward shot. Keep generated photos at the same aspect ratio and similar background tones so the collection page grid feels cohesive."""

PURSE_MODEL_PROMPT = """Purses prompt
Using the uploaded product photo as reference, create a high-end ecommerce lifestyle product photograph featuring the same handbag worn by a model.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. The bag is the primary subject; the model is there to provide scale and styling context.
- Adapt the background tone, wardrobe colors, and lighting warmth to complement the bag's natural color palette. Each generated photo should feel cohesive with its specific product, not a repeating template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: A confident Black woman in her late 20s, shown from chest to mid-thigh (the purse must be fully visible and centered in the frame but not too big). She is holding the purse naturally, holding, not strapped on her shoulder. Face may be partially cropped or shown - prioritize the bag's visibility.

Wardrobe: Elegant, modern outfit in neutral or complementary tones (cream, beige, soft brown, muted terracotta, or off-white). Subtle African print accent allowed (a sleeve detail, scarf, or trim) but the outfit should NOT compete with the bag. Simple, clean silhouette.

Composition: Vertical or square framing. Model slightly off-center to leave breathing room. Bag positioned at the visual focal point, roughly center of frame. Three-quarter front angle on the bag so handles, body, and side profile are visible.

Background: Seamless, minimal, lightly textured surface (warm plaster wall, soft linen backdrop, or stone). Tone chosen to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side for depth. Highlights catch the bag's leather grain, fabric weave, and hardware. True-to-life color on the bag - no filters or color shifts that would misrepresent the product.

Mood: Premium, editorial, modern - like a Polene, Mansur Gavriel, or Brother Vellies lifestyle campaign.

Style: High-end commercial fashion photography, photorealistic, sharp focus on the bag, shallow depth of field. Slight imperfections, natural skin texture, realistic hands holding the bag correctly.

Aspect ratio: 4:5 (vertical, for product grid and listing pages).
Resolution: high detail, every stitch and texture on the bag visible."""

_ON_MODEL_PROMPTS = {
    "purse": PURSE_MODEL_PROMPT,
    "handbag": ON_MODEL_PROMPT,
    "tote": ON_MODEL_PROMPT,
    "suitcase": ON_MODEL_PROMPT,
    "other": ON_MODEL_PROMPT,
}


async def _edit_with_reference(
    reference_images: list[tuple[bytes, str]],
    prompt: str,
    fidelity_rules: str,
    count: int,
    size: str,
    style_references: list[tuple[bytes, str]] | None = None,
) -> list[bytes]:
    """Return generated PNG candidates from an OpenAI image edit call.

    `reference_images` are THE PRODUCT (reproduce exactly). Optional
    `style_references` are approved store images used for scene/look only. They
    are appended after the product images and explicitly labeled STYLE-ONLY in
    the prompt so the model matches their look without copying the exemplar's
    product (the "product bleed" failure mode).
    """
    if not _openai:
        raise RuntimeError("OPENAI_API_KEY is not configured")
    if count <= 0:
        return []

    style_references = style_references or []
    product_pngs = [_to_png(image_bytes) for image_bytes, _ in reference_images]
    style_pngs = [_to_png(image_bytes) for image_bytes, _ in style_references]

    role_note = ""
    if style_pngs:
        role_note = (
            "\n\nIMAGE ROLES:\n"
            f"- The first {len(product_pngs)} image(s) are THE PRODUCT. Reproduce that "
            "exact product — shape, color, hardware, logo, stitching, texture, and "
            "proportions — with total fidelity.\n"
            f"- The final {len(style_pngs)} image(s) are STYLE REFERENCES from our store. "
            "Match their scene, background, lighting, composition, framing, and model "
            "styling. DO NOT copy their product, product color, or hardware. If a style "
            "reference shows a different product, ignore that product entirely."
        )
    full_prompt = f"{prompt}\n\n{fidelity_rules}{role_note}"
    upload_bytes = product_pngs + style_pngs

    def _call() -> list[bytes]:
        image_payload = [
            (f"reference_{index}.png", io.BytesIO(image), "image/png")
            for index, image in enumerate(upload_bytes)
        ]
        edit_kwargs = dict(
            model=settings.image_model,
            image=image_payload[0] if len(image_payload) == 1 else image_payload,
            prompt=full_prompt,
            n=count,
            size=size,
            quality=settings.image_quality,
        )
        # input_fidelity is a gpt-image-1-only knob: better product/logo
        # preservation at a token-cost premium. Off by default (see config).
        if settings.image_input_fidelity and settings.image_model == "gpt-image-1":
            edit_kwargs["input_fidelity"] = settings.image_input_fidelity
        result = _openai.images.edit(**edit_kwargs)
        return [
            base64.b64decode(item.b64_json)
            for item in result.data
            if item.b64_json
        ]

    return await asyncio.to_thread(_call)


async def generate_lifestyle(
    reference_images: list[tuple[bytes, str]],
    prompt_pack: ProductPromptPack = BAG_PROMPT_PACK,
    count: int | None = None,
    style_references: list[tuple[bytes, str]] | None = None,
) -> list[bytes]:
    """Return simple lifestyle candidates. Best-effort; review before use."""
    return await _edit_with_reference(
        reference_images=reference_images,
        prompt=prompt_pack.lifestyle_prompt,
        fidelity_rules=prompt_pack.fidelity_rules,
        count=settings.lifestyle_candidates if count is None else count,
        size=settings.lifestyle_image_size,
        style_references=style_references,
    )


async def generate_on_model(
    reference_images: list[tuple[bytes, str]],
    product_kind: str = "handbag",
    prompt_pack: ProductPromptPack = BAG_PROMPT_PACK,
    count: int | None = None,
    style_references: list[tuple[bytes, str]] | None = None,
) -> list[bytes]:
    """Return on-model candidates. Best-effort; review before use."""
    if product_kind == "purse" and prompt_pack.purse_model_prompt:
        prompt = prompt_pack.purse_model_prompt
    else:
        prompt = prompt_pack.model_prompt
    if not prompt:
        return []
    return await _edit_with_reference(
        reference_images=reference_images,
        prompt=prompt,
        fidelity_rules=prompt_pack.fidelity_rules,
        count=settings.on_model_candidates if count is None else count,
        size=settings.on_model_image_size,
        style_references=style_references,
    )
