"""Image generation. Three outputs, three reliability tiers:

  clean_white_bg()    -> Real product pixels, white background.
                         Photoroom is strongest; rembg is a local low-cost option.
                         This is your safe primary catalog image.

  generate_lifestyle()-> BEST-EFFORT. The exact product in a simple ecommerce scene
                         without hands/model complexity.

  generate_on_model() -> BEST-EFFORT. A model using/holding/wearing the product, generated by a
                         reference-conditioned image model (image edits:
                         the real product photo is the input, so the product is preserved
                         rather than hallucinated). Returns several candidates;
                         a human picks the good ones before publish. Some outputs
                         WILL mangle hardware/logo or warp the product near hands —
                         that's expected, hence candidates + review.

Claude does NOT generate images — the generated-image provider is OpenAI here.
To move to Gemini later, reimplement the edit helper only; orchestration stays.
"""

import asyncio
import base64
import io

import httpx
from openai import OpenAI
from PIL import Image, ImageOps

from app.config import settings
from app.product_types.prompts import BAG_PROMPT_PACK, ProductPromptPack

_openai = OpenAI(api_key=settings.openai_api_key) if settings.openai_api_key else None

_EXT_BY_MEDIA_TYPE = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
}


def _to_png(image_bytes: bytes) -> bytes:
    """Normalize uploads for providers that reject unusual image modes."""
    with Image.open(io.BytesIO(image_bytes)) as image:
        image = ImageOps.exif_transpose(image)
        if image.mode not in ("RGB", "RGBA"):
            image = image.convert("RGBA" if "A" in image.getbands() else "RGB")

        output = io.BytesIO()
        image.save(output, format="PNG")
        return output.getvalue()


# --- White-bg shot -----------------------------------------------------------

async def clean_white_bg(image_bytes: bytes, media_type: str) -> bytes:
    """Product composited onto a clean white background."""
    backend = settings.background_remover.lower().strip()
    if backend == "rembg":
        return await _clean_white_bg_rembg(image_bytes)
    if backend == "photoroom":
        return await _clean_white_bg_photoroom(image_bytes)
    raise RuntimeError(
        "BACKGROUND_REMOVER must be 'photoroom' or 'rembg' "
        f"(got {settings.background_remover!r})"
    )


async def _clean_white_bg_rembg(image_bytes: bytes) -> bytes:
    """Local background removal using rembg, then composite onto white."""
    upload_bytes = _to_png(image_bytes)

    def _call() -> bytes:
        try:
            from rembg import remove
        except ImportError as exc:
            raise RuntimeError(
                "rembg is not installed. Run: pip install -r requirements.txt"
            ) from exc

        cutout_bytes = remove(upload_bytes)
        with Image.open(io.BytesIO(cutout_bytes)) as cutout:
            cutout = ImageOps.exif_transpose(cutout).convert("RGBA")
            white = Image.new("RGBA", cutout.size, (255, 255, 255, 255))
            white.alpha_composite(cutout)
            output = io.BytesIO()
            white.convert("RGB").save(output, format="PNG")
            return output.getvalue()

    return await asyncio.to_thread(_call)


async def _clean_white_bg_photoroom(image_bytes: bytes) -> bytes:
    """Product composited onto a clean white background using Photoroom Basic.

    Photoroom Remove Background API:
        POST https://sdk.photoroom.com/v1/segment
        headers: {"x-api-key": settings.photoroom_api_key}
        files:   {"image_file": (filename, image_bytes, media_type)}
        -> transparent-background PNG bytes in the response body

    The API only removes the background. We composite the returned transparent
    PNG onto white locally so we do not need the Image Editing API.
    """
    if not settings.photoroom_api_key:
        raise RuntimeError("PHOTOROOM_API_KEY is not configured")

    upload_bytes = _to_png(image_bytes)
    last_exc: Exception | None = None
    async with httpx.AsyncClient(timeout=60) as client:
        for attempt in range(3):
            try:
                response = await client.post(
                    "https://sdk.photoroom.com/v1/segment",
                    headers={"x-api-key": settings.photoroom_api_key},
                    files={"image_file": ("product.png", upload_bytes, "image/png")},
                )
                break
            except (
                httpx.ConnectError,
                httpx.ReadError,
                httpx.RemoteProtocolError,
                httpx.TimeoutException,
            ) as exc:
                last_exc = exc
                if attempt == 2:
                    raise
                await asyncio.sleep(1 + attempt)
        else:
            raise RuntimeError(f"Photoroom failed before response: {last_exc}")

    if response.status_code >= 400:
        raise RuntimeError(
            f"Photoroom failed with {response.status_code}: {response.text}"
        )

    with Image.open(io.BytesIO(response.content)) as cutout:
        cutout = ImageOps.exif_transpose(cutout).convert("RGBA")
        white = Image.new("RGBA", cutout.size, (255, 255, 255, 255))
        white.alpha_composite(cutout)
        output = io.BytesIO()
        white.convert("RGB").save(output, format="PNG")
        return output.getvalue()


# --- Best-effort generated shots (reference-conditioned image editing) -------

PRODUCT_FIDELITY_RULES = """Product fidelity rules:
- If multiple reference photos are provided, they are different angles of the same exact product. Use all of them to understand the product's true 3D shape, side profile, handle/strap placement, depth, hardware, texture, and proportions. Do not combine them into multiple products.
- Preserve the exact outer silhouette and proportions of the reference product. If the reference is heart-shaped, crescent, boxy, rectangular, rounded, slouchy, structured, mini, oversized, or asymmetrical, the generated product must keep that same shape.
- Do not stretch, slim, widen, round off, square off, or simplify the bag. Do not change handle height, flap shape, clasp placement, strap attachment points, chain length, side profile, corner radius, or base width.
- Keep distinctive details in the same locations: clasp, lock, logo, seams, stitches, studs, beads, rhinestones, quilting, pleats, panels, piping, handles, strap, feet, zipper, and hardware.
- Treat the uploaded image as a product reference, not design inspiration. The scene may change, but the product design may not."""

LIFESTYLE_PRODUCT_PROMPT = """Product picture with no model
Using the uploaded product photo as reference, create a clean, high-end ecommerce product photograph of the same handbag.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. This is a product listing image, not a stylized reinterpretation.
- Adapt the background tone, lighting warmth, and shadow style to complement the bag's natural color palette. A warm leather bag should sit on a warm-toned backdrop; a cool-toned bag on a softer neutral. Each product photo should feel cohesive with its own product, not a uniform template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: The handbag presented on its own as the sole subject. No model, no hands, no extra props. The bag is upright and styled naturally (handles resting, slight side angle showing depth and profile).

Composition: Bag centered in frame with breathing room on all sides. Three-quarter front angle so handles, body, and one side panel are all visible. Slight elevation - shot just above the bag's midpoint.

Background: Seamless, minimal, lightly textured surface (linen, matte paper, soft plaster, or warm stone). Tone selected to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side to give depth. Highlights catch the leather grain, fabric weave, or hardware. Bright enough to show true color, soft enough to avoid harsh reflections.

Mood: Premium, editorial, clean - like a Mansur Gavriel, Polene, or Brother Vellies catalog image.

Style: High-end commercial product photography, photorealistic, sharp focus on the product, shallow depth of field, natural grain. Colors must be true-to-life (no over-saturation or filter look).

Aspect ratio: 1:1 (square, for product grid).
Resolution: high detail, every stitch and texture visible."""

ON_MODEL_PROMPT = """Product picture with model
Using the uploaded product photo as reference, create a high-end ecommerce lifestyle product photograph featuring the same handbag worn by a model.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. The bag is the primary subject; the model is there to provide scale and styling context.
- Adapt the background tone, wardrobe colors, and lighting warmth to complement the bag's natural color palette. Each generated photo should feel cohesive with its specific product, not a repeating template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: A confident Black woman in her late 20s, shown from chest to mid-thigh (the bag must be fully visible and centered in the frame). She is holding the bag naturally - by the top handle at her side, on her shoulder, or in the crook of her arm, depending on the bag style. Her pose is relaxed and elegant, not overly posed. Face may be partially cropped or shown - prioritize the bag's visibility.

Wardrobe: Elegant, modern outfit in neutral or complementary tones (cream, beige, soft brown, muted terracotta, or off-white). Subtle African print accent allowed (a sleeve detail, scarf, or trim) but the outfit should NOT compete with the bag. Simple, clean silhouette.

Composition: Vertical or square framing. Model slightly off-center to leave breathing room. Bag positioned at the visual focal point, roughly center of frame. Three-quarter front angle on the bag so handles, body, and side profile are visible.

Background: Seamless, minimal, lightly textured surface (warm plaster wall, soft linen backdrop, or stone). Tone chosen to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side for depth. Highlights catch the bag's leather grain, fabric weave, and hardware. True-to-life color on the bag - no filters or color shifts that would misrepresent the product.

Mood: Premium, editorial, modern - like a Polene, Mansur Gavriel, or Brother Vellies lifestyle campaign.

Style: High-end commercial fashion photography, photorealistic, sharp focus on the bag, shallow depth of field. Slight imperfections, natural skin texture, realistic hands holding the bag correctly.

Aspect ratio: 4:5 (vertical, for product grid and listing pages).
Resolution: high detail, every stitch and texture on the bag visible.

Run one bag at a time with a single reference photo for best fidelity. Close attention to anatomically correct hands holding the bag handle. Generate variation through natural pose only: one candidate holding by the handle, one candidate with the bag on the shoulder where appropriate, one detail-oriented product-forward shot. Keep generated photos at the same aspect ratio and similar background tones so the collection page grid feels cohesive."""

PURSE_MODEL_PROMPT = """Purses prompt
Using the uploaded product photo as reference, create a high-end ecommerce lifestyle product photograph featuring the same handbag worn by a model.

IMPORTANT:
- The handbag must match the exact design, color, texture, hardware, stitching, and proportions of the uploaded reference photo. Do not alter the product - replicate it faithfully. The bag is the primary subject; the model is there to provide scale and styling context.
- Adapt the background tone, wardrobe colors, and lighting warmth to complement the bag's natural color palette. Each generated photo should feel cohesive with its specific product, not a repeating template.
- Do not add brand names, store names, text, watermarks, labels, or logos anywhere in the image.

Scene: A confident Black woman in her late 20s, shown from chest to mid-thigh (the purse must be fully visible and centered in the frame but not too big). She is holding the purse naturally, holding, not strapped on her shoulder. Face may be partially cropped or shown - prioritize the bag's visibility.

Wardrobe: Elegant, modern outfit in neutral or complementary tones (cream, beige, soft brown, muted terracotta, or off-white). Subtle African print accent allowed (a sleeve detail, scarf, or trim) but the outfit should NOT compete with the bag. Simple, clean silhouette.

Composition: Vertical or square framing. Model slightly off-center to leave breathing room. Bag positioned at the visual focal point, roughly center of frame. Three-quarter front angle on the bag so handles, body, and side profile are visible.

Background: Seamless, minimal, lightly textured surface (warm plaster wall, soft linen backdrop, or stone). Tone chosen to complement the bag - cream, sand, taupe, soft terracotta, or mocha. No furniture, no clutter, no text, no logos.

Lighting: Soft diffused daylight from one side, gentle natural shadow on the opposite side for depth. Highlights catch the bag's leather grain, fabric weave, and hardware. True-to-life color on the bag - no filters or color shifts that would misrepresent the product.

Mood: Premium, editorial, modern - like a Polene, Mansur Gavriel, or Brother Vellies lifestyle campaign.

Style: High-end commercial fashion photography, photorealistic, sharp focus on the bag, shallow depth of field. Slight imperfections, natural skin texture, realistic hands holding the bag correctly.

Aspect ratio: 4:5 (vertical, for product grid and listing pages).
Resolution: high detail, every stitch and texture on the bag visible."""

_ON_MODEL_PROMPTS = {
    "purse": PURSE_MODEL_PROMPT,
    "handbag": ON_MODEL_PROMPT,
    "tote": ON_MODEL_PROMPT,
    "suitcase": ON_MODEL_PROMPT,
    "other": ON_MODEL_PROMPT,
}


async def _edit_with_reference(
    reference_images: list[tuple[bytes, str]],
    prompt: str,
    fidelity_rules: str,
    count: int,
    size: str,
) -> list[bytes]:
    """Return generated PNG candidates from an OpenAI image edit call."""
    if not _openai:
        raise RuntimeError("OPENAI_API_KEY is not configured")
    if count <= 0:
        return []

    upload_bytes = [_to_png(image_bytes) for image_bytes, _ in reference_images]
    full_prompt = f"{prompt}\n\n{fidelity_rules}"

    def _call() -> list[bytes]:
        image_payload = [
            (f"reference_{index}.png", io.BytesIO(image), "image/png")
            for index, image in enumerate(upload_bytes)
        ]
        result = _openai.images.edit(
            model=settings.image_model,
            image=image_payload[0] if len(image_payload) == 1 else image_payload,
            prompt=full_prompt,
            n=count,
            size=size,
            quality=settings.image_quality,
        )
        return [
            base64.b64decode(item.b64_json)
            for item in result.data
            if item.b64_json
        ]

    return await asyncio.to_thread(_call)


async def generate_lifestyle(
    reference_images: list[tuple[bytes, str]],
    prompt_pack: ProductPromptPack = BAG_PROMPT_PACK,
    count: int | None = None,
) -> list[bytes]:
    """Return simple lifestyle candidates. Best-effort; review before use."""
    return await _edit_with_reference(
        reference_images=reference_images,
        prompt=prompt_pack.lifestyle_prompt,
        fidelity_rules=prompt_pack.fidelity_rules,
        count=settings.lifestyle_candidates if count is None else count,
        size=settings.lifestyle_image_size,
    )


async def generate_on_model(
    reference_images: list[tuple[bytes, str]],
    product_kind: str = "handbag",
    prompt_pack: ProductPromptPack = BAG_PROMPT_PACK,
    count: int | None = None,
) -> list[bytes]:
    """Return on-model candidates. Best-effort; review before use."""
    if product_kind == "purse" and prompt_pack.purse_model_prompt:
        prompt = prompt_pack.purse_model_prompt
    else:
        prompt = prompt_pack.model_prompt
    if not prompt:
        return []
    return await _edit_with_reference(
        reference_images=reference_images,
        prompt=prompt,
        fidelity_rules=prompt_pack.fidelity_rules,
        count=settings.on_model_candidates if count is None else count,
        size=settings.on_model_image_size,
    )
