"""Guided store setup — scaffold a new store/client's .env in one step.

    python -m app.init

Walks through the values a new store needs, writes them to `.env` (the per-store
config, gitignored), and then optionally validates the Shopify credentials and
builds that store's copy/image example corpus.

Learning-first split: the wizard (prompting + writing .env) is implemented so the
command runs today. The two backend-meaningful pieces are yours to fill in — look
for `TODO(chris)`:
  1. _validate_shopify() — do the client-credentials token exchange live.
  2. _build_corpus()     — chain the example builders after setup.
"""

from __future__ import annotations

import argparse
import asyncio
import subprocess
import sys
from dataclasses import dataclass
from getpass import getpass
from pathlib import Path

import httpx

ENV_PATH = Path(".env")


@dataclass(frozen=True)
class Field:
    key: str
    label: str
    default: str = ""
    secret: bool = False
    required: bool = True


# The values a new store needs. Order = order asked = order written.
FIELDS: tuple[Field, ...] = (
    Field("BRAND_NAME", "Store / brand name (drives listing voice + SEO suffix)"),
    Field("ANTHROPIC_API_KEY", "Anthropic API key (Claude copy)", secret=True),
    Field("OPENAI_API_KEY", "OpenAI API key (gpt-image generation)", secret=True),
    Field("BACKGROUND_REMOVER", "Background remover [photoroom/pixelcut/rembg]",
          default="photoroom"),
    Field("PHOTOROOM_API_KEY", "Photoroom API key", secret=True, required=False),
    Field("PIXELCUT_API_KEY", "Pixelcut API key", secret=True, required=False),
    Field("SHOPIFY_STORE", "Shopify store domain (xxx.myshopify.com)"),
    Field("SHOPIFY_CLIENT_ID", "Shopify app client ID", secret=True),
    Field("SHOPIFY_CLIENT_SECRET", "Shopify app client secret", secret=True),
    Field("SHOPIFY_API_VERSION", "Shopify API version", default="2026-04"),
)

_SHOPIFY_KEYS = ("SHOPIFY_STORE", "SHOPIFY_CLIENT_ID", "SHOPIFY_CLIENT_SECRET")


# --------------------------------------------------------------------------- #
# .env read / write (implemented)
# --------------------------------------------------------------------------- #

def _load_existing_env(path: Path) -> dict[str, str]:
    """Parse an existing .env into {KEY: value}, so a re-run can offer current
    values as defaults. Blank lines and `# comments` are skipped."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def _prompt_value(field: Field, current: str) -> str:
    """Ask for one field. Enter keeps the current/default value.

    Secrets are read without echo and shown only as `(set)` when already present.
    """
    if field.secret:
        shown_default = "(set)" if current else (field.default or "")
        suffix = f" [{shown_default}]" if shown_default else ""
        entered = getpass(f"{field.label}{suffix}: ")
    else:
        shown_default = current or field.default
        suffix = f" [{shown_default}]" if shown_default else ""
        entered = input(f"{field.label}{suffix}: ").strip()

    if not entered:
        return current or field.default
    return entered


def _write_env(path: Path, values: dict[str, str]) -> None:
    """Write .env from FIELDS values, preserving any pre-existing unknown keys.

    Existing file is backed up to .env.bak first so a mistaken re-run is
    recoverable.
    """
    known = {f.key for f in FIELDS}
    preserved = {
        k: v for k, v in _load_existing_env(path).items() if k not in known
    }

    if path.exists():
        path.replace(path.with_suffix(".bak"))

    lines = ["# Generated by `python -m app.init`. One .env per store. Do not commit.\n"]
    for field in FIELDS:
        value = values.get(field.key, "")
        lines.append(f"{field.key}={value}")
    if preserved:
        lines.append("\n# Preserved from your previous .env:")
        lines.extend(f"{k}={v}" for k, v in preserved.items())

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)  # secrets — owner read/write only


# --------------------------------------------------------------------------- #
# TODO(chris): the backend pieces
# --------------------------------------------------------------------------- #

async def _validate_shopify(values: dict[str, str]) -> tuple[bool | None, str]:
    """Confirm the Shopify creds work by minting an Admin token.

    Uses the values the user just entered (NOT app.config.settings — that was
    loaded from the OLD .env at import time, so it won't reflect this run).

        POST https://{SHOPIFY_STORE}/admin/oauth/access_token
        form body: grant_type=client_credentials,
                   client_id=SHOPIFY_CLIENT_ID,
                   client_secret=SHOPIFY_CLIENT_SECRET
        200 -> {"access_token": "shpat_...", "scope": ..., "expires_in": 86399}

    Returns (True, scope) on success, (False, error) on a bad response/network
    error, or (None, reason) when there's nothing to check.
    """
    store = values.get("SHOPIFY_STORE", "")
    client_id = values.get("SHOPIFY_CLIENT_ID", "")
    client_secret = values.get("SHOPIFY_CLIENT_SECRET", "")
    if not (store and client_id and client_secret):
        return None, "no Shopify credentials to check"

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"https://{store}/admin/oauth/access_token",
                data={
                    "grant_type": "client_credentials",
                    "client_id": client_id,
                    "client_secret": client_secret,
                },
            )
    except httpx.HTTPError as exc:
        return False, f"network error: {exc}"

    if resp.status_code >= 400:
        return False, f"{resp.status_code}: {resp.text[:200]}"

    scope = resp.json().get("scope", "")
    return True, f"token minted (scope: {scope or 'n/a'})"


def _build_corpus() -> bool:
    """Build this store's copy + image example corpus after setup.

    Chains the two existing builders so a fresh store is fully seeded:
      1. app.shopify_examples         -> products.raw.jsonl + listing_examples.jsonl
      2. app.services.image_examples  -> image_examples.jsonl (downloads + tags)

    Each runs as a subprocess so it loads the .env we just wrote — importing them
    in-process would reuse the settings already loaded from the OLD .env. Returns
    True only if both steps succeed.
    """
    steps = ("app.shopify_examples", "app.services.image_examples")
    for module in steps:
        print(f"  -> {module}")
        result = subprocess.run([sys.executable, "-m", module])
        if result.returncode != 0:
            print(f"  {module} failed (exit {result.returncode}) — stopping.")
            return False
    return True


# --------------------------------------------------------------------------- #
# Orchestration (implemented)
# --------------------------------------------------------------------------- #

def _missing_required(values: dict[str, str]) -> list[str]:
    return [f.key for f in FIELDS if f.required and not values.get(f.key)]


def main() -> None:
    parser = argparse.ArgumentParser(description="Set up a new store's .env.")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing .env without confirming.")
    parser.add_argument("--no-validate", action="store_true",
                        help="Skip the live Shopify credential check.")
    parser.add_argument("--build-corpus", action="store_true",
                        help="Build the copy/image example corpus after setup.")
    args = parser.parse_args()

    if ENV_PATH.exists() and not args.force:
        answer = input(f"{ENV_PATH} already exists — update it? [y/N] ").strip().lower()
        if answer not in {"y", "yes"}:
            print("Aborted.")
            return

    existing = _load_existing_env(ENV_PATH)
    print("\nEnter values (press Enter to keep the shown default):\n")
    values = {f.key: _prompt_value(f, existing.get(f.key, "")) for f in FIELDS}

    missing = _missing_required(values)
    if missing:
        print(f"\nMissing required values: {', '.join(missing)}. Nothing written.")
        return

    _write_env(ENV_PATH, values)
    print(f"\nWrote {ENV_PATH} (previous version backed up to {ENV_PATH}.bak).")

    if not args.no_validate:
        ok, message = asyncio.run(_validate_shopify(values))
        icon = {True: "OK", False: "FAILED", None: "SKIPPED"}[ok]
        print(f"Shopify credentials: {icon} — {message}")

    if args.build_corpus:
        print("Building example corpus...")
        if _build_corpus():
            print("Corpus built.")

    print("\nDone. Next: drop product photos in incoming/<type>/ and run "
          "`python -m app.batch --limit 1 --creative both`.")


if __name__ == "__main__":
    main()
